// Captures the screenshots for the governance/platform features documented in
// docs/USER-MANUAL.md that the other suites don't produce: the Jobs console
// (§5.14), the Audit log, and the Encryption vault (both §6). Each page reads
// from chrome.storage.local and/or OPFS, so we seed a small, realistic sample
// through the same shapes the app writes (ba_jobs / OPFS report.md; ba_audit_index
// / OPFS audit JSONL) and then screenshot. Deterministic and offline — no model
// call is needed for any of these pages. Screenshots land in
// docs/user-guide/screenshots/ and are committed as documentation evidence.

import { expect, test } from './fixtures';

const SHOTS = 'docs/user-guide/screenshots';
const DESKTOP = { width: 1280, height: 900 };

test.describe('governance & platform screenshots', () => {
  test('Jobs console — durable research jobs with progress and a report', async ({ context, extensionId, sidebar }) => {
    void sidebar; // seeds ba_settings so the console chrome renders configured
    const page = await context.newPage();
    await page.setViewportSize(DESKTOP);
    await page.goto(`chrome-extension://${extensionId}/workspace.html#jobs`);

    // Seed a small catalogue plus the finished job's report in OPFS, exactly as
    // jobStore writes them (ba_jobs + /jobs/{id}/report.md).
    await page.evaluate(async () => {
      const now = Date.now();
      const limits = { maxSources: 60, maxDepth: 2, maxConcurrency: 3, perItemMaxSteps: 6, elapsedCapMs: 4 * 60 * 60 * 1000 };
      const jobs = [
        {
          id: 'job-running-1', type: 'research', title: 'EV battery supply-chain risks (2024–2026)',
          objective: 'Exhaustively research emerging supply-chain risks for EV batteries.',
          status: 'running', limits,
          createdAt: now - 95_000, startedAt: now - 95_000, updatedAt: now - 3_000,
          processed: 12, pending: 8,
        },
        {
          id: 'job-done-1', type: 'research', title: 'Global undersea-cable outages: causes & mitigations',
          objective: 'Survey recent undersea-cable outages and mitigation strategies.',
          status: 'done', limits,
          createdAt: now - 3_600_000, startedAt: now - 3_600_000, updatedAt: now - 600_000, finishedAt: now - 600_000,
          processed: 34, pending: 0, reportName: 'undersea-cable-outages-report.md',
        },
        {
          id: 'job-paused-1', type: 'research', title: 'Open-source LLM licences compared',
          objective: 'Compare the licences of major open-source LLMs.',
          status: 'paused', limits,
          createdAt: now - 300_000, startedAt: now - 300_000, updatedAt: now - 120_000,
          processed: 5, pending: 15,
        },
      ];
      await chrome.storage.local.set({ ba_jobs: jobs });

      const report = [
        '# Global undersea-cable outages: causes & mitigations',
        '',
        'Across 34 sources reviewed, three causes account for most recent outages:',
        '',
        '1. **Anchor and fishing-gear damage** in shallow shelf waters — the single',
        '   largest category, concentrated on a handful of congested straits [1][2].',
        '2. **Deliberate or suspected sabotage**, a growing share since 2023 [3].',
        '3. **Undersea landslides and seismic events**, rarer but high-impact [4].',
        '',
        '## Mitigations that recur across the literature',
        '',
        '- Route diversity and mesh topologies so no single break isolates a region.',
        '- Faster repair-ship availability agreements and pre-positioned spares.',
        '- Protective burial and armouring in high-traffic shelf zones.',
        '',
        '_Sources: 34 pages, cited inline. Generated by a deep research job._',
        '',
      ].join('\n');
      const root = await navigator.storage.getDirectory();
      const jobsDir = await root.getDirectoryHandle('jobs', { create: true });
      const jd = await jobsDir.getDirectoryHandle('job-done-1', { create: true });
      const fh = await jd.getFileHandle('report.md', { create: true });
      const w = await fh.createWritable();
      await w.write(report);
      await w.close();
    });

    await page.reload();
    await expect(page.getByRole('heading', { name: 'Jobs', exact: true })).toBeVisible();
    await expect(page.getByText('EV battery supply-chain risks (2024–2026)')).toBeVisible();

    // Open the finished job's report so the screenshot shows list + report.
    await page.getByRole('button', { name: 'View report' }).first().click();
    await expect(page.locator('.ws-job-report pre')).toContainText('undersea-cable outages');

    await page.screenshot({ path: `${SHOTS}/06-jobs-console.png` });
    await page.close();
  });

  test('Audit log — a conversation record of policy decisions and tool calls', async ({ context, extensionId, sidebar }) => {
    void sidebar;
    const page = await context.newPage();
    await page.setViewportSize(DESKTOP);
    await page.goto(`chrome-extension://${extensionId}/workspace.html#audit`);

    // Seed one conversation's audit file (OPFS JSONL) + the ba_audit_index row,
    // exactly as auditLog.appendAuditEvent writes them.
    await page.evaluate(async () => {
      const convId = 'a1b2c3d4-demo-research-session';
      const base = Date.now() - 5 * 60_000;
      const iso = (offsetMs: number) => new Date(base + offsetMs).toISOString();
      const events = [
        { eventId: 'e1', timestamp: iso(0), conversationId: convId, eventType: 'POLICY_DECISION', tool: 'open_url', target: { origin: 'https://example.com' }, inputDigest: '9f2c1a77b0', outputDigest: '3d81ee40aa', policyDecision: 'allow', result: 'success', durationMs: 38 },
        { eventId: 'e2', timestamp: iso(1_400), conversationId: convId, eventType: 'TOOL_EXECUTED', tool: 'get_tab_content', target: { origin: 'https://example.com' }, inputDigest: '11aa22bb33', outputDigest: 'c40de5f6a1', policyDecision: 'allow', result: 'success', durationMs: 126 },
        { eventId: 'e3', timestamp: iso(2_900), conversationId: convId, eventType: 'APPROVAL_REQUESTED', tool: 'click_element', target: { origin: 'https://example.com' }, inputDigest: 'aa77bb88cc', policyDecision: 'needs_approval' },
        { eventId: 'e4', timestamp: iso(9_500), conversationId: convId, eventType: 'APPROVAL_GRANTED', tool: 'click_element', approvalId: 'apr-2571', policyDecision: 'allow' },
        { eventId: 'e5', timestamp: iso(9_900), conversationId: convId, eventType: 'TOOL_EXECUTED', tool: 'click_element', target: { origin: 'https://example.com' }, inputDigest: 'aa77bb88cc', outputDigest: '77e1f0ba22', policyDecision: 'allow', result: 'success', durationMs: 305 },
        { eventId: 'e6', timestamp: iso(14_200), conversationId: convId, eventType: 'TOOL_DENIED', tool: 'call_mcp_tool', target: { origin: 'https://tickets.internal' }, inputDigest: 'de01ad99f2', policyDecision: 'deny', policyRule: 'unattended_requires_approval', result: 'denied', unattended: true },
      ];
      const jsonl = events.map((e) => JSON.stringify(e)).join('\n') + '\n';
      const root = await navigator.storage.getDirectory();
      const dir = await root.getDirectoryHandle('audit', { create: true });
      const fh = await dir.getFileHandle(`${convId}.jsonl`, { create: true });
      const w = await fh.createWritable();
      await w.write(jsonl);
      await w.close();
      await chrome.storage.local.set({
        ba_audit_index: [
          { conversationId: convId, count: events.length, bytes: new TextEncoder().encode(jsonl).byteLength, firstTs: events[0].timestamp, lastTs: events[events.length - 1].timestamp },
        ],
      });
    });

    await page.reload();
    await expect(page.getByRole('heading', { name: 'Audit', exact: true })).toBeVisible();
    // Open the seeded conversation's log, then wait for the events table.
    await page.locator('.ws-audit-convo').first().click();
    await expect(page.locator('.ws-audit-table')).toBeVisible();
    await expect(page.locator('.ws-audit-table tbody tr')).toHaveCount(6);

    await page.screenshot({ path: `${SHOTS}/07-audit-log.png` });
    await page.close();
  });

  test('Encryption vault — enable passphrase encryption at rest', async ({ context, extensionId, sidebar }) => {
    void sidebar; // ba_settings seeded so the Models page renders configured
    const page = await context.newPage();
    await page.setViewportSize(DESKTOP);
    await page.goto(`chrome-extension://${extensionId}/workspace.html#models`);

    const vault = page.locator('.ws-vault-section');
    await expect(vault.getByText('Encryption vault')).toBeVisible();
    await expect(vault.getByRole('button', { name: 'Enable encryption' })).toBeVisible();

    await vault.screenshot({ path: `${SHOTS}/08-encryption-vault.png` });
    await page.close();
  });
});
